"use client";

import React, { useEffect, useRef, useState } from "react";
import { ArrowUpRight, AudioLines, ChevronDown, Command, Headphones, Mic, MicOff, Send, ShieldCheck, Sparkles, Volume2, VolumeX, Waves, X } from "lucide-react";
import { Button } from "../components/Button";
import styles from "./_index.module.css";

type ChatMessage = { role: "user" | "assistant"; content: string };
type SpeechRecognitionResultEvent = Event & { resultIndex: number; results: SpeechRecognitionResultList };
type SpeechRecognitionLike = { continuous: boolean; interimResults: boolean; lang: string; maxAlternatives: number; onresult: ((event: SpeechRecognitionResultEvent) => void) | null; onerror: ((event: Event & { error?: string }) => void) | null; onend: (() => void) | null; start: () => void; stop: () => void; abort: () => void };
type SpeechWindow = Window & { SpeechRecognition?: new () => SpeechRecognitionLike; webkitSpeechRecognition?: new () => SpeechRecognitionLike };
const starters = ["Help me bring an idea to life", "What do you remember about my goals?", "Help me think something through"];

export default function HomePage() {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [draft, setDraft] = useState(""); const [interim, setInterim] = useState("");
  const [listening, setListening] = useState(false); const [thinking, setThinking] = useState(false); const [speaking, setSpeaking] = useState(false);
  const [voiceEnabled, setVoiceEnabled] = useState(true); const [notice, setNotice] = useState(""); const [showTranscript, setShowTranscript] = useState(true);
  const recognitionRef = useRef<SpeechRecognitionLike | null>(null); const pendingTranscriptRef = useRef(""); const bottomRef = useRef<HTMLDivElement | null>(null); const inputRef = useRef<HTMLTextAreaElement | null>(null);
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth", block: "end" }); }, [messages, interim, thinking]);
  useEffect(() => () => { recognitionRef.current?.abort(); if (typeof window !== "undefined") window.speechSynthesis?.cancel(); }, []);

  const speak = async (text: string) => {
    if (!voiceEnabled || typeof window === "undefined") return;
    window.speechSynthesis?.cancel(); setSpeaking(true);
    try {
      const response = await fetch("/api/voice", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text }) });
      if (!response.ok) throw new Error("voice unavailable");
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const audio = new Audio(url);
      audio.onended = () => { URL.revokeObjectURL(url); setSpeaking(false); };
      audio.onerror = () => { URL.revokeObjectURL(url); setSpeaking(false); };
      await audio.play();
    } catch {
      if (!window.speechSynthesis) { setSpeaking(false); return; }
      const utterance = new SpeechSynthesisUtterance(text); utterance.rate = 0.96; utterance.pitch = 1.02;
      utterance.onend = () => setSpeaking(false); utterance.onerror = () => setSpeaking(false); window.speechSynthesis.speak(utterance);
    }
  };
  const sendMessage = async (raw: string) => {
    const content = raw.trim(); if (!content || thinking) return;
    recognitionRef.current?.stop(); setListening(false); setInterim(""); setDraft(""); setNotice("");
    const nextMessages: ChatMessage[] = [...messages, { role: "user", content }]; setMessages(nextMessages); setThinking(true);
    try {
      const response = await fetch("/api/intelligence-chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: nextMessages.slice(-12) }) });
      const data = await response.json(); if (!response.ok) throw new Error(data?.error || "The Intelligence could not respond just now.");
      const answer = String(data.reply || "I'm here. Tell me a little more about what you need."); setMessages((current) => [...current, { role: "assistant", content: answer }]); speak(answer);
    } catch (error) { setNotice(error instanceof Error ? error.message : "Connection interrupted. Please try again."); }
    finally { setThinking(false); }
  };
  const startListening = () => {
    if (listening) { recognitionRef.current?.stop(); setListening(false); return; }
    const speechWindow = window as SpeechWindow; const Recognition = speechWindow.SpeechRecognition || speechWindow.webkitSpeechRecognition;
    if (!Recognition) { setNotice("Live transcription is not supported in this browser. Try Chrome or Edge, or type your message below."); return; }
    window.speechSynthesis?.cancel(); setSpeaking(false); setNotice(""); setInterim(""); pendingTranscriptRef.current = "";
    const recognition = new Recognition(); recognition.lang = navigator.language || "en-US"; recognition.continuous = false; recognition.interimResults = true; recognition.maxAlternatives = 1;
    recognition.onresult = (event) => { let finalText = ""; let liveText = ""; for (let i = event.resultIndex; i < event.results.length; i++) { const result = event.results[i]; if (result.isFinal) finalText += result[0].transcript; else liveText += result[0].transcript; } if (liveText) setInterim(liveText); if (finalText.trim()) { pendingTranscriptRef.current = `${pendingTranscriptRef.current} ${finalText}`.trim(); setDraft((current) => `${current} ${finalText}`.trim()); setInterim(""); } };
    recognition.onerror = (event) => { setListening(false); if (event.error === "not-allowed") setNotice("Microphone access is blocked. Allow microphone access in your browser settings and try again."); else if (event.error !== "no-speech" && event.error !== "aborted") setNotice("I couldn't hear that clearly. Please try again."); };
    recognition.onend = () => { setListening(false); const transcript = pendingTranscriptRef.current.trim(); pendingTranscriptRef.current = ""; if (transcript) void sendMessage(transcript); }; recognitionRef.current = recognition;
    try { recognition.start(); setListening(true); } catch { setListening(false); setNotice("The microphone could not start. Please try again."); }
  };
  const stopSpeaking = () => { window.speechSynthesis?.cancel(); setSpeaking(false); };

  return <main className={styles.appShell}>
    <header className={styles.topbar}>
      <a className={styles.brand} href="#top" aria-label="Zyoran home"><span className={styles.brandMark}><span /></span><span className={styles.brandWords}><strong>ZYORAN</strong><small>THE UNIVERSE</small></span></a>
      <nav className={styles.topNav} aria-label="Main navigation"><a href="/intelligence" className={styles.navActive}>The Intelligence</a><a href="/now">Now</a><a href="/memory">Memory fabric</a><a href="/projects">Projects</a></nav>
      <div className={styles.topActions}><span className={styles.privatePill}><ShieldCheck size={13} /> Private by design</span><Button variant="ghost" size="icon" aria-label={voiceEnabled ? "Mute voice responses" : "Enable voice responses"} onClick={() => { setVoiceEnabled((v) => !v); if (voiceEnabled) stopSpeaking(); }}>{voiceEnabled ? <Volume2 size={17} /> : <VolumeX size={17} />}</Button><Button variant="outline" size="md" className={styles.topCta} onClick={() => { inputRef.current?.focus(); document.getElementById("experience")?.scrollIntoView({ behavior: "smooth" }); }}>Meet her <ArrowUpRight size={15} /></Button></div>
    </header>
    <section className={styles.hero} id="top"><div className={styles.heroCopy}><div className={styles.eyebrow}><span className={styles.liveDot} /> A NEW KIND OF INTELLIGENCE</div><h1>More than an answer.<br /><em>A mind beside yours.</em></h1><p className={styles.heroLead}>Meet The Intelligence — a personal intelligence partner built to understand your context, remember what matters, and help you make what comes next possible.</p><div className={styles.heroButtons}><Button size="lg" onClick={() => { document.getElementById("experience")?.scrollIntoView({ behavior: "smooth" }); inputRef.current?.focus(); }}>Start a conversation <ArrowUpRight size={17} /></Button><a className={styles.quietLink} href="#principles">Explore the idea <span>↓</span></a></div><div className={styles.heroFootnote}><span className={styles.footLine} /> Built around you, not just your prompts</div></div>
      <div className={styles.heroVisual} aria-label="Abstract illustration of connected intelligence"><div className={styles.visualGrid} /><div className={`${styles.orbit} ${styles.orbitOuter}`} /><div className={`${styles.orbit} ${styles.orbitMid}`} /><div className={`${styles.orbit} ${styles.orbitInner}`} /><div className={styles.orbGlow} /><div className={styles.coreOrb}><div className={styles.coreShine} /><div className={styles.coreEye} /></div><span className={`${styles.node} ${styles.nodeOne}`} /><span className={`${styles.node} ${styles.nodeTwo}`} /><span className={`${styles.node} ${styles.nodeThree}`} /><div className={styles.visualCaption}><span>01 / INTELLIGENCE</span><span>Always in context</span></div></div><div className={styles.heroIndex}><span>01</span><span className={styles.indexRule} /><span>THE BEGINNING</span></div></section>
    <section className={styles.experience} id="experience"><div className={styles.sectionHeading}><div><div className={styles.eyebrow}>YOUR SPACE TO THINK</div><h2>Meet <em>THE INTELIGENCE.</em></h2></div><p>Speak naturally. She listens, transcribes your words, and responds with a voice of her own.</p></div>
      <div className={styles.chatLayout}><aside className={styles.chatAside}><div className={styles.asideTop}><span className={styles.asideLabel}>YOUR INTELLIGENCE</span><span className={styles.statusBadge}><span /> {listening ? "Listening" : speaking ? "Speaking" : thinking ? "Thinking" : "Ready"}</span></div><div className={`${styles.avatarStage} ${listening ? styles.avatarListening : speaking ? styles.avatarSpeaking : thinking ? styles.avatarThinking : ""}`}><div className={styles.avatarHalo} /><div className={styles.avatarRing} /><div className={styles.avatarOrb}><div className={styles.avatarLight} /><div className={styles.avatarLine} /></div><span className={styles.avatarStar}>✳</span></div><div className={styles.identity}><h3>The Intelligence</h3><p>ASTARA · AUREN</p></div><div className={styles.presence}><span className={styles.presenceDot} /> Here with you <span className={styles.presenceDivider}>/</span> In context</div><div className={styles.asideDivider} />
        <div className={styles.capability}><span className={styles.capIcon}><Headphones size={16} /></span><div><strong>Voice, naturally</strong><small>Speak as you think. No special commands.</small></div></div><div className={styles.capability}><span className={styles.capIcon}><Waves size={16} /></span><div><strong>Words, made visible</strong><small>Your speech appears as live text.</small></div></div><div className={styles.capability}><span className={styles.capIcon}><ShieldCheck size={16} /></span><div><strong>You stay in control</strong><small>Microphone only listens when you start.</small></div></div><div className={styles.voiceToggle}><span><Volume2 size={15} /> Spoken responses</span><button className={`${styles.switch} ${voiceEnabled ? styles.switchOn : ""}`} onClick={() => { setVoiceEnabled((v) => !v); if (voiceEnabled) stopSpeaking(); }} aria-label="Toggle spoken responses" aria-pressed={voiceEnabled}><span /></button></div></aside>
        <div className={styles.chatPanel}><div className={styles.chatHeader}><div><span className={styles.chatHeaderTitle}>A conversation with her</span><span className={styles.chatHeaderSub}>A private space for your next thought</span></div><button className={styles.transcriptToggle} onClick={() => setShowTranscript((v) => !v)}>{showTranscript ? "Hide transcript" : "Show transcript"}<ChevronDown size={14} /></button></div><div className={styles.messageArea}>
          {messages.length === 0 ? <div className={styles.welcomeState}><div className={styles.welcomeMark}><Sparkles size={17} /></div><div className={styles.messageMeta}>THE INTELLIGENCE <span>·</span> JUST NOW</div><p className={styles.welcomeMessage}>I'm here. What are you thinking about today?</p><p className={styles.welcomeHint}>You can speak to me or type below. I'll be listening when you choose to begin.</p><div className={styles.starterList}>{starters.map((starter) => <button key={starter} className={styles.starter} onClick={() => void sendMessage(starter)}>{starter}<ArrowUpRight size={14} /></button>)}</div></div> : <div className={styles.messages}>{messages.map((message, index) => <article key={`${index}-${message.role}`} className={`${styles.message} ${message.role === "user" ? styles.userMessage : styles.assistantMessage}`}><div className={styles.messageMeta}>{message.role === "user" ? "YOU" : "THE INTELLIGENCE"}<span>·</span>{message.role === "user" ? "YOUR WORDS" : "RESPONSE"}</div>{showTranscript ? <p>{message.content}</p> : <p className={styles.transcriptHidden}>{message.role === "user" ? "Voice message transcribed" : "Spoken response"}</p>}{message.role === "assistant" && <button className={styles.replayButton} onClick={() => speak(message.content)}><Volume2 size={13} /> Play voice</button>}</article>)}{thinking && <div className={styles.thinkingRow}><span className={styles.thinkingDots}><i /><i /><i /></span><span>The Intelligence is thinking…</span></div>}</div>}
          {interim && <div className={styles.liveTranscript}><span className={styles.transcriptPulse} /><div><span>LIVE TRANSCRIPTION</span><p>{interim}</p></div></div>}{notice && <div className={styles.notice}><span>{notice}</span><button onClick={() => setNotice("")} aria-label="Dismiss notice"><X size={14} /></button></div>}<div ref={bottomRef} /></div>
        <div className={styles.composerWrap}>{listening && <div className={styles.listeningBanner}><span className={styles.listeningBars}><i /><i /><i /><i /><i /></span><span>I'm listening — speak naturally</span><button onClick={() => recognitionRef.current?.stop()}>Finish</button></div>}<div className={styles.composer}><textarea ref={inputRef} value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void sendMessage(draft); } }} placeholder={listening ? "Your words will appear here…" : "Share what's on your mind…"} rows={1} aria-label="Message The Intelligence" /><div className={styles.composerActions}><span className={styles.composerHint}><Command size={11} /> Enter to send <span>·</span> Shift + Enter for a new line</span><div className={styles.composerButtons}><Button variant={listening ? "destructive" : "outline"} size="icon-lg" className={styles.micButton} onClick={startListening} aria-label={listening ? "Stop listening" : "Start voice input"}>{listening ? <MicOff size={18} /> : <Mic size={18} />}</Button><Button size="icon-lg" className={styles.sendButton} disabled={!draft.trim() || thinking} onClick={() => void sendMessage(draft)} aria-label="Send message"><Send size={17} /></Button></div></div></div><div className={styles.composerFooter}><span><span className={styles.secureDot} /> Your conversation stays yours</span><span>{voiceEnabled ? "Voice responses on" : "Text responses only"}</span></div></div></div></div>
      <p className={styles.browserNote}><AudioLines size={14} /> Voice input transcribes in your browser and sends the finished phrase for a spoken reply. Microphone permission is requested only when you tap the mic.</p></section>
    <section className={styles.principles} id="principles"><div className={styles.eyebrow}>NOT ANOTHER CHATBOT</div><h2>Intelligence that understands<br /><em>the space between things.</em></h2><div className={styles.principleGrid}><article><span>01 / CONTEXT</span><h3>Understand the why.</h3><p>Your words matter. The goals, constraints, and circumstances around them matter just as much.</p></article><article id="memory"><span>02 / MEMORY</span><h3>Remember what matters.</h3><p>Important context can return when it becomes relevant — not simply because it was said before.</p></article><article><span>03 / MOMENTUM</span><h3>Move ideas forward.</h3><p>Turn a thought into a clearer plan, a creative direction, or a meaningful next step.</p></article></div></section>
    <footer className={styles.footer}><a className={styles.brand} href="#top"><span className={styles.brandMark}><span /></span><span className={styles.brandWords}><strong>ZYORAN</strong><small>THE UNIVERSE</small></span></a><span className={styles.footerTag}>A universe of possibility. Intelligence beside you.</span><span className={styles.footerRight}>THE INTELIGENCE <span>© 2026</span></span></footer>
  </main>;
}
