import React from "react";
import { SiteShell } from "./SiteShell";
import { EmptyState, Metric, SectionTitle, SignalCard, TimelineRow } from "./CommandBlocks";
import styles from "./CommandView.module.css";

type ViewKey = "now" | "next" | "projects" | "memory" | "intelligence" | "agents" | "learning" | "effect";

const config: Record<ViewKey, { eyebrow: string; title: React.ReactNode; description: string; metrics: [string,string,string][]; cards: [string,string,string,string,string][] }> = {
  now: { eyebrow: "COMMAND CENTER / NOW", title: <>What is <em>alive</em> right now?</>, description: "A calm view of the work, context, and intelligence that deserves your attention in this moment.", metrics: [["Active context","04","threads with current relevance"],["Signals","07","new observations"],["Open loops","03","waiting for a next move"]], cards: [["ACTIVE","Your current idea","The thought you brought into the conversation is still unresolved. Keep the thread open while the shape becomes clearer.","CONTEXT","Continue"],["SIGNAL","A useful connection","A prior constraint appears relevant to the direction you are exploring now.","MEMORY","Review"],["NEXT","One small move","There is enough clarity to turn the current thought into a concrete next action.","MOMENTUM","Open"]] },
  next: { eyebrow: "COMMAND CENTER / NEXT", title: <>The next move, <em>not every move.</em></>, description: "Prioritized actions emerge from context, evidence, and your stated goals — without pretending certainty where there is none.", metrics: [["Ready now","03","small, high-clarity actions"],["Waiting","02","blocked by missing input"],["Later","06","useful but non-urgent"]], cards: [["01","Clarify the outcome","Write the one sentence that defines what success looks like for the current project.","HIGH CLARITY","Start"],["02","Review a recalled constraint","A dormant memory has returned with a different scope. Confirm whether it still applies.","VERIFY","Review"],["03","Turn research into a plan","A cluster of evidence is ready to become a structured working brief.","READY","Open"]] },
  projects: { eyebrow: "COMMAND CENTER / PROJECTS", title: <>Work with a <em>memory.</em></>, description: "Projects keep goals, decisions, evidence, and outcomes together so the Intelligence can understand the work across time.", metrics: [["Active","04","projects in motion"],["Paused","02","waiting for a decision"],["Outcomes","11","recorded since start"]], cards: [["ACTIVE","Zyoran public experience","Shape the public expression of the Intelligence and the larger universe without collapsing the two into one product.","ACTIVE","Open"],["ACTIVE","Memory Fabric","Build contextual recall with provenance, scope, dormancy, and re-evaluation.","ACTIVE","Open"],["PAUSED","Naming system","Keep naming research separate from architecture until clearance decisions are explicit.","PAUSED","Review"]] },
  memory: { eyebrow: "COMMAND CENTER / MEMORY", title: <>Remembered, but never <em>assumed.</em></>, description: "Memory is durable context with scope, provenance, confidence, and lifecycle — not a transcript dump.", metrics: [["Active","18","memories currently relevant"],["Dormant","31","retained for future relevance"],["Needs review","04","scope or freshness changed"]], cards: [["CONTEXT","A recurring preference","Stored with its original scope and the context in which it was useful.","ACTIVE","Inspect"],["DORMANT","An earlier project constraint","Retained after the original project ended so it can be reconsidered if that context returns.","DORMANT","Re-evaluate"],["REVIEW","A changing assumption","Later evidence may have weakened the original claim. It should not silently influence a recommendation.","VERIFY","Review"]] },
  intelligence: { eyebrow: "COMMAND CENTER / INTELLIGENCE", title: <>From evidence to <em>understanding.</em></>, description: "Research, patterns, beliefs, insights, and recommendations remain distinct — connected by provenance rather than blended into one answer.", metrics: [["Evidence","24","recent source items"],["Insights","09","supported observations"],["Recommendations","05","awaiting your judgment"]], cards: [["RESEARCH","A new source cluster","Several sources converge on the same underlying constraint. The system keeps the source trail visible.","EVIDENCE","Inspect"],["INSIGHT","The pattern beneath the work","A repeated friction point appears across related project contexts.","SUPPORTED","Explore"],["RECOMMENDATION","A possible next move","A recommendation is presented with the evidence and context that caused it to surface.","EXPLAINABLE","Review"]] },
  agents: { eyebrow: "COMMAND CENTER / AGENTS", title: <>Agents with <em>clear boundaries.</em></>, description: "Role-based work can move forward while permissions, approvals, provenance, and human control remain explicit.", metrics: [["Running","02","bounded tasks"],["Waiting","01","needs approval"],["Completed","14","logged outcomes"]], cards: [["RUNNING","Research scout","Collecting and organizing evidence for a defined question. No external action is implied.","READ","Inspect"],["WAITING","Action planner","Has prepared a proposed action but is waiting for your approval before execution.","APPROVAL","Review"],["COMPLETE","Context mapper","Connected relevant project material and recorded the provenance of the relationship.","DONE","Inspect"]] },
  learning: { eyebrow: "COMMAND CENTER / LEARNING", title: <>Turn experience into <em>mastery.</em></>, description: "Learning candidates are reviewed rather than silently promoted. The system helps you decide what deserves to become durable knowledge.", metrics: [["In review","05","candidate learnings"],["Mastered","12","confirmed concepts"],["Paused","03","learning intentionally paused"]], cards: [["REVIEW","A concept worth keeping","A repeated explanation across several contexts suggests this knowledge may deserve a durable place.","CANDIDATE","Review"],["MASTERED","A working principle","Confirmed knowledge that can now be retrieved when the relevant context returns.","CONFIRMED","Inspect"],["PAUSED","A noisy topic","Learning is paused here; no automatic promotion should occur while that preference is active.","PAUSED","Inspect"]] },
  effect: { eyebrow: "COMMAND CENTER / EFFECT", title: <>See what actually <em>changed.</em></>, description: "Outcomes close the loop. The system tracks whether actions reduced friction, improved clarity, or produced the result you intended.", metrics: [["Closed loops","17","outcomes recorded"],["Friction reduced","38%","across measured workflows"],["Evidence gaps","06","results still uncertain"]], cards: [["OUTCOME","A decision became simpler","The user chose a direction after the relevant evidence and constraints were made visible.","RECORDED","Inspect"],["OUTCOME","A project regained momentum","A dormant context returned and prevented repeated discovery work.","RECORDED","Inspect"],["MEASURE","An assumption remains open","The intended effect has not been verified yet, so the system keeps the claim provisional.","UNVERIFIED","Review"]] },
};

export function CommandView({ view }: { view: ViewKey }) {
  const c = config[view];
  return <SiteShell active={view} eyebrow={c.eyebrow} title={c.title} description={c.description}>
    <div className={styles.metricGrid}>{c.metrics.map((m) => <Metric key={m[0]} label={m[0]} value={m[1]} detail={m[2]} />)}</div>
    <SectionTitle index="01" title={view === "now" ? "Signals in context" : "Working surface"} note="Nothing here is treated as more certain than its evidence allows." />
    <div className={styles.cardGrid}>{c.cards.map((card) => <SignalCard key={card[1]} eyebrow={card[0]} title={card[1]} body={card[2]} tag={card[3]} action={card[4]} />)}</div>
    <SectionTitle index="02" title="Activity" note="A traceable record of what moved, changed, or is waiting." />
    <div className={styles.timeline}>
      <TimelineRow time="Just now" title="Context refreshed" body="The current working context was re-evaluated before surfacing these signals." status="active" />
      <TimelineRow time="Earlier" title="Evidence connected" body="Relevant source material was linked to the active project with provenance preserved." status="done" />
      <TimelineRow time="Queued" title="Outcome review" body="A future result will be checked against the intention that created the action." status="queued" />
    </div>
    <SectionTitle index="03" title="If there is nothing to act on" />
    <EmptyState title="No forced action." body="The Intelligence should be useful without manufacturing activity. When context is incomplete, it can wait, ask, or show what is missing." />
  </SiteShell>;
}
